### ISSUE TITLE
Publisher callback backup with high throughput

### ISSUE THREAD

**Issue by eoneal89** [nats-io/nats.js#371] opened 2020-08-31 15:43 UTC
We are unable to achieve adequate throughput while waiting for publish acknowledgement callbacks. Everything works fine until we hit around 100 messages/second (it also depends on how many connections we have open). It seems like the way the callback is implemented after a flush happens, that the callbacks should be resolving at regular intervals. 

When we have high, sustained throughput though, sometimes we wait for 5 or 6 seconds for a publish callback to be resolved (even though we see the message come through to a subscriber within a second or so). Is there a better way for us to implement publishing callbacks for large throughput?

**Comment by aricart** [comment] 2020-08-31 19:52
@eoneal89 If I understand correctly, you have a subscription listening on the same message that you are publishing, you are then publishing a message followed up by a `flush()`. You see the subscription process the message you sent, but the callback specified to your `flush` is not getting called until later.

If that is the case I am suspecting that your application is not returning from the message callback, and I am suspecting that very quickly after your subscription callback returns, your flush callback happens. If you block the event loop of the subscription handler, the client will not be able to process any other message.

**Comment by derekcollison** [comment] 2020-08-31 20:08
Do you have a short example of your code you could share?

**Comment by aricart** [comment] 2020-08-31 20:08
Here's an example:
```javascript
const { connect, createInbox } = require("nats");

const nc = connect();
nc.on("connect", () => {
  const subj = createInbox();
  const start = Date.now();
  nc.subscribe(subj, (data) => {
    console.log(`a - sub: ${Date.now() - start} ms`);
  });
  nc.publish(subj);
  nc.flush(() => {
    console.log(`a - flush: ${Date.now() - start} ms`);
  });
  nc.drain();
});

const nc2 = connect();
nc2.on("connect", () => {
  const subj = createInbox();
  const start = Date.now();
  nc2.subscribe(subj, (data) => {
    console.log(`b - sub: ${Date.now() - start} ms`);
    for (let i = 0; i < 100000000; i++) {
    }
  });
  nc2.publish(subj);
  nc2.flush(() => {
    console.log(`b - flush: ${Date.now() - start} ms`);
  });
  nc2.drain();
});
```

On a local system, running this prints:
```bash
b - sub: 1 ms
b - flush: 73 ms
a - sub: 0 ms
a - flush: 0 ms
```

**Comment by aricart** [comment] 2020-08-31 20:19
Another important thing is that if for every interaction you are publishing a `flush` you are will adversely affect your performance, as the OS/Kernel will limit the number of system calls that you can make. If you allow the client to buffer your messages as you should, the client will send your messages on the next event loop.

If you are flushing to ensure that your message went out, you still should consider sending out a request instead. The response from the system to which the message was intended is the only way you'll really know if your message was received (otherwise the server might have received it, but that doesn't answer to whether your intended application did).

**Comment by eoneal89** [comment] 2020-09-08 19:29
I apologize for the poor wording on my part. I didn't mean to say that we were calling `flush` after every publish, but that I expected the publish callback to be called a lot faster than I was seeing because of the way the library is flushing.

**Comment by eoneal89** [comment] 2020-09-08 19:34
I apologize for the poor wording on my part. I didn't mean to say that we were calling flush after every publish, but that I expected the publish callback to be called a lot faster than I was seeing because of the way the library is flushing.

Here is an example of what we were doing. We had 5 concurrent connections that were just publishing, and one subscriber. 

```const { connect } = require('nats');
const EVENT_COUNT = 1000

// PUBLISHERS
const publish = async () => {
  const nc = connect();
  nc.on('connect', () => {
    for (let i = 0; i < EVENT_COUNT; i++) {
      const start = Date.now()
      nc.publish('test', `PUBLISHER 2 MESSAGE #${i}`, () => {
        console.log('PUB2 Time: ', Date.now() - start)
      });
    }
  });

  const nc2 = connect();
  nc2.on('connect', () => {
    for (let i = 0; i < EVENT_COUNT; i++) {
      const start = Date.now()
      nc2.publish('test', `PUBLISHER 2 MESSAGE #${i}`, () => {
        console.log('PUB2 Time: ', Date.now() - start)
      });
    }
  });

  const nc3 = connect();
  nc3.on('connect', () => {
    for (let i = 0; i < EVENT_COUNT; i++) {
      const start = Date.now()
      nc3.publish('test', `PUBLISHER 3 MESSAGE #${i}`, () => {
        console.log('PUB3 Time: ', Date.now() - start)
      });
    }
  });

  const nc4 = connect();
  nc4.on('connect', () => {
    for (let i = 0; i < EVENT_COUNT; i++) {
      const start = Date.now()
      nc4.publish('test', `PUBLISHER 4 MESSAGE #${i}`, () => {
        console.log('PUB4 Time: ', Date.now() - start)
      });
    }
  });

  const nc5 = connect();
  nc5.on('connect', () => {
    for (let i = 0; i < EVENT_COUNT; i++) {
      const start = Date.now()
      nc5.publish('test', `PUBLISHER 5 MESSAGE #${i}`, () => {
        console.log('PUB5 Time: ', Date.now() - start)
      });
    }
  });
}

// SUBSCRIBER

const nc6 = connect();
new Promise((resolve, reject) => nc6.on('connect', () => {
  console.log('subscriber connected')
  console.time('overall')
  nc6.subscribe('test', (data) => {
    if (data === 'PUBLISHER 1 MESSAGE #999') console.timeEnd('overall')
    console.log('subscribe callback', data)
  })
  resolve()
}))
  .then(() => publish())
  .then(() => console.log('done'))
```

However, after creating this example, I realized that the callback timing was much faster under the same load so it wasn't the library, but rather something else in our application was clogging our event loop. 

The example above does have an increase in time as more events are published though, and so we decided to follow some previous advice from your team to use `.request()` with a callback instead of `.publish()` and that has led to more stability under high load.

Thanks for the help, this issue can be closed.

**Comment by aricart** [comment] 2020-09-17 15:32
@eoneal89 your current use working using the beta async features?

**Comment by aricart** [comment] 2020-09-18 21:40
@eoneal89 going to close the issue - feel free to reopen if you have any updates!

**Closed by aricart** 2020-09-18 21:40 UTC
