### ISSUE TITLE
High (variant) delay JetStream.publish method ver 2.14.0

### ISSUE THREAD

**Issue by johanfol** [nats-io/nats.js#573] opened 2023-05-27 23:19 UTC
Hi, firstly, thanks for all the nice docs!

Setup:
Running Nats in Docker for Windows
Producer: nodejs app running "version": "2.14.0" of Nats, from command line. 

Issue: I've implemented a JetStream with retention set to Interest, storage specified as Memory, and sending a Uint8Array(3855) size message like so:

```
  const server = {
      servers: configuration.serverUrl,
  };
  
  // to create a connection to a nats-server:
  const natsConn = await connect(server);
  console.log(`connected to ${natsConn.getServer()}`);
  // this promise indicates the client closed
  const done = natsConn.closed();
  
  // Jetstream setup
  const jsm = await natsConn.jetstreamManager();
  const streamName = "RuleRequest";
  await jsm.streams.find(streamName).then((s) => {
      console.log("Stream already exists");
  }, async (reason) => {
      // Create Stream
      const cfg: Partial<StreamConfig> = {
          name: streamName,
          subjects: [streamName],
          retention: RetentionPolicy.Interest,
          storage: StorageType.Memory,
      };
      await jsm.streams.add(cfg)
      console.log("Created the stream")
  });
      
  // create connection to JetStream
  const js = natsConn.jetstream();    
  // create Uint8Array(3855) sized request buffer
  const toSend = sc.encode(req);
  
  for (let iteration = 0; iteration < 10; iteration++) {
      console.time('PublishRuleRequest');
      const resp = await js.publish("RuleRequest", toSend);
      console.timeEnd('PublishRuleRequest');
  }
  
  }); 
```
 
With or without consumers registered, the console.time timer has variant response times. On average, it takes about ~16ms to post to an empty Nats server (with JetStream enabled). But, here's the funky part, few requests will take ~2ms (which is more what I'm expecting). Why do most of the requests take so long to send, when one or two in a batch of 10 occasionally are reasonably quick (2ms)? Here's a random batch's outcome:

```
PublishRuleRequest: 13.935ms
PublishRuleRequest: 2.172ms
PublishRuleRequest: 16.82ms
PublishRuleRequest: 17.466ms
PublishRuleRequest: 17.863ms
PublishRuleRequest: 18.201ms
PublishRuleRequest: 17.223ms
PublishRuleRequest: 17.903ms
PublishRuleRequest: 18.319ms
PublishRuleRequest: 17.668ms
```

On the same environment, just doing plain Nats pub/sub, the publish events take <1ms. So the ~2ms is understandable since JetStream does more than Nats, but the ~16ms average doesn't sound right, especially considering some messages are quick. Am I missing something?

**Comment by johanfol** [comment] 2023-05-27 23:37
Update, above test is running the Producer from command line, from the Windows host, communicating to the Nats server running inside docker for Windows. 

When running the same Producer from within the Docker instance, above responses are more consistent, faster than the ~16ms average, significantly faster. Is this more the expected time it should take for a JetStream to process a ~4kb message? 

```
2023-05-28 01:31:42 connected to host.docker.internal:4222
2023-05-28 01:31:42 PublishRuleRequest: 3.657ms
2023-05-28 01:31:42 PublishRuleRequest: 5.349ms
2023-05-28 01:31:42 PublishRuleRequest: 5.259ms
2023-05-28 01:31:42 PublishRuleRequest: 4.474ms
2023-05-28 01:31:42 PublishRuleRequest: 3.999ms
2023-05-28 01:31:43 PublishRuleRequest: 3.749ms
2023-05-28 01:31:43 PublishRuleRequest: 4.45ms
2023-05-28 01:31:43 PublishRuleRequest: 4.75ms
2023-05-28 01:31:43 PublishRuleRequest: 3.787ms
2023-05-28 01:31:43 PublishRuleRequest: 3.974ms
```

**Comment by aricart** [comment] 2023-06-05 19:48
@johanfol - not sure what the jump between subsystems between docker and windows does - but one thing that possibly needs to be separated is the rtt() of the client/server from the actual JetStream processing - The client has an `rtt()` function that returns the rtt for the connection. The rtt() is going to be in milliseconds, if you want to do better than that, do a flush() bracketed by the console.time as you are doing. With those measurements, you may be able to get more insight into how long the jetstream operation takes.

**Comment by aricart** [comment] 2023-08-16 15:40
@johanfol the issue is indeed fixed by https://github.com/nats-io/nats.deno/pull/566

```javascript
const start = performance.now();
  for (let i=0; i < 10000; i++) {
    await js.publish("hello.a");
  }
  const time = performance.now() - start;
  t.log(time, time/1000);
```
Before the fix:
```
 ✔ jetstream › jetstream - pub time (1.8s)
    ℹ 1637.265547990799 1.637265547990799
```

After:
```
✔ jetstream › jetstream - pub time (13.8s)
    ℹ 13740.07334804535 13.74007334804535
  ─
```

**Closed by aricart** 2023-08-16 15:40 UTC
